### ISSUE TITLE
index.template.php Error

### ISSUE THREAD

**Issue by Adonix44** [siddhartha-gupta/SMF-Likes#39]
This mod is not able to install on other themes. Showing error  "./Themes/demo/index.template.php	Test failed.

I tried on 3-4 themes, in every theme this one error is coming "index.template.php error"

i checked index.template.php, there is no code which needs to be found. But i found some different code which was matching littlebit with code that needs to be found.

http://s21.postimg.org/6vevplqd3/Capture.jpg

I also tried to manually edit index.template.php, i added this below code after above code, but forum broke. not worked :(

http://s30.postimg.org/4ney8sfnl/Capture1.jpg

Please help, make this mod work with all themes :(

**Comment by saurabh1938** [comment]
I am facing the same issue :(

**Comment by siddhartha-gupta** [comment]
Basically every theme customises index.template.php mainly, hence for most of the custom theme you need to make the edit manually only.
