### ISSUE TITLE
Not pretty url friendly

### ISSUE THREAD

**Issue by siddhartha-gupta** [siddhartha-gupta/SMF-Likes#41]
http://www.simplemachines.org/community/index.php?topic=506743.msg3804381#msg3804381

**Comment by Al-eXs** [comment]
I suggest that change the `<a href="#"` to `<span` in the HTML of the link, and then add a CSS rule like this:
>.showLikeNotification:hover {
>    text-decoration: underline;
>}

That should solve the issue with PrettyURLs, that was what I've done in my site.

**Comment by siddhartha-gupta** [comment]
@Al-eXs thanks a lot. Made the changes
